language: node_js
node_js:
- 8.11.3
env:
  global:
  - NODE_PATH="src/"
  - NODE_ENV=test
  - TOKEN_COOKIE_NAME=test_token
  - AUTH_SECRET=secret
  - JWT_EXPIRES_IN='1 day'
before_install: if [[ `npm -v` != 6.1.0 ]]; then npm i -g npm@6.1.0; fi
install:
- npm run ci-install
script:
- npm run lint
- npm test
deploy:
  provider: heroku
  api_key:
    secure: Ypb9DgIDEws1T8P9HoGbsCcKK6FhTFYEDb4+DHzmi16eDdzCMiXRMI1z0WLfp1smF2ZqayjS9dUHFb2Cb+rfFMyUilXmg3B5ggGzj8dWwNERa7kCdGG8jV/5py9pmHJn8CWC/27NutEzmxCBiwF8rtMhuOadFeOOQn/pRua8UC/LyXG4vWyvmoCdfOVGdZf60DYOGKUlukggNKB102vIc+nnjMMVlsXkKwREOephfaEmGfZvy1a+nEJAzv7SL13GfuVV6C+cxD577DtOW9V69uGH6tWqjzR9mTmjdmeu4inM8No20Wpk8HPw7SeiWaeitjnhPDiTecnzMoeluWn7Nxnd1Grxl77SZ2aIQgQG+5Z7ZoPnz7HrmfCvXqba1xL75R1kqWn/0lrCMt14uLc0Y7E9GdTdnFdNuD7LYtu4szkImXGuy/9t90DE3BlUIJ5OiungHPzpBxtCV1RwxTr9UtQXJmqjMQHCUQgUApvnUHTmh9ocAoXpQ5i1HTlVSVkVCybE+Q7XQlyc+2pUbu4mzfnAuDGRf43JnbGgP3zayXuEJvIhN4bKn8g6o+TfrZM8sBeeZJdAYuUbu2HZpwcrYZ2bcT0Jp1lPuE8SdceDkwuJog7eLiCs0FrPzGZLGL0BR5/Wg43Xx/U9P3VX+KXrqoxOGhwg7suKxF0GKBq2DZc=
  app: ssn-app-staging
  run:
    - "npm run db:clean"
    - "npm run db:seed"
